[2022-09-01 22:11:44,236] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-09-01T22:11:43.037970+00:00 [queued]>
[2022-09-01 22:11:44,248] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-09-01T22:11:43.037970+00:00 [queued]>
[2022-09-01 22:11:44,249] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-01 22:11:44,250] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-01 22:11:44,251] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-01 22:11:44,268] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_run_file> on 2022-09-01 22:11:43.037970+00:00
[2022-09-01 22:11:44,276] {standard_task_runner.py:52} INFO - Started process 94452 to run task
[2022-09-01 22:11:44,281] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'waiting_for_run_file', 'manual__2022-09-01T22:11:43.037970+00:00', '--job-id', '3710', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpm1oamptu', '--error-file', '/tmp/tmpngoskqw9']
[2022-09-01 22:11:44,282] {standard_task_runner.py:80} INFO - Job 3710: Subtask waiting_for_run_file
[2022-09-01 22:11:44,376] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-09-01T22:11:43.037970+00:00 [running]> on host 9d5d2a77e6ba
[2022-09-01 22:11:44,480] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=waiting_for_run_file
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T22:11:43.037970+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-01T22:11:43.037970+00:00
[2022-09-01 22:11:44,494] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-09-01 22:11:44,495] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-09-01 22:11:54,500] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-09-01 22:11:54,501] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-09-01 22:12:04,527] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-09-01 22:12:04,528] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-09-01 22:12:14,548] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-09-01 22:12:14,549] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-09-01 22:12:14,551] {filesystem.py:63} INFO - Found File /opt/***/dags/test.txt last modified: 20220901221205
[2022-09-01 22:12:14,552] {base.py:301} INFO - Success criteria met. Exiting.
[2022-09-01 22:12:14,570] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=trigger_sensor, task_id=waiting_for_run_file, execution_date=20220901T221143, start_date=20220901T221144, end_date=20220901T221214
[2022-09-01 22:12:14,599] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-09-01 22:12:14,608] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 94452. PIDs of all processes in the group: [94452]
[2022-09-01 22:12:14,613] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 94452
[2022-09-01 22:12:14,617] {process_utils.py:75} INFO - Process psutil.Process(pid=94452, status='terminated', exitcode=0, started='22:11:43') (94452) terminated with exit code 0
