[2022-09-08 17:41:50,618] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tables_name_1.check_table_exist manual__2022-09-08T17:41:47.003996+00:00 [queued]>
[2022-09-08 17:41:50,633] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tables_name_1.check_table_exist manual__2022-09-08T17:41:47.003996+00:00 [queued]>
[2022-09-08 17:41:50,635] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-08 17:41:50,635] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-08 17:41:50,636] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-08 17:41:50,657] {taskinstance.py:1397} INFO - Executing <Task(BranchPythonOperator): check_table_exist> on 2022-09-08 17:41:47.003996+00:00
[2022-09-08 17:41:50,665] {standard_task_runner.py:52} INFO - Started process 5366 to run task
[2022-09-08 17:41:50,670] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tables_name_1', 'check_table_exist', 'manual__2022-09-08T17:41:47.003996+00:00', '--job-id', '4042', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpkxf_dqll', '--error-file', '/tmp/tmpellrt54c']
[2022-09-08 17:41:50,671] {standard_task_runner.py:80} INFO - Job 4042: Subtask check_table_exist
[2022-09-08 17:41:50,758] {task_command.py:371} INFO - Running <TaskInstance: tables_name_1.check_table_exist manual__2022-09-08T17:41:47.003996+00:00 [running]> on host 4a46d6ca03fb
[2022-09-08 17:41:50,851] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tables_name_1
AIRFLOW_CTX_TASK_ID=check_table_exist
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T17:41:47.003996+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T17:41:47.003996+00:00
[2022-09-08 17:41:50,867] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-09-08 17:41:50,875] {jobs_dag.py:62} INFO - THIS IS FIRST QUERY:
[2022-09-08 17:41:50,876] {jobs_dag.py:63} INFO - [('public', 'alembic_version', '***', None, True, False, False, False), ('public', 'dag', '***', None, True, False, True, False), ('public', 'log', '***', None, True, False, False, False), ('public', 'dag_pickle', '***', None, True, False, False, False), ('public', 'import_error', '***', None, True, False, False, False), ('public', 'job', '***', None, True, False, False, False), ('public', 'connection', '***', None, True, False, False, False), ('pg_catalog', 'pg_statistic', '***', None, True, False, False, False), ('pg_catalog', 'pg_type', '***', None, True, False, False, False), ('public', 'sla_miss', '***', None, True, False, False, False), ('public', 'slot_pool', '***', None, True, False, False, False), ('pg_catalog', 'pg_foreign_table', '***', None, True, False, False, False), ('pg_catalog', 'pg_authid', '***', 'pg_global', True, False, False, False), ('public', 'variable', '***', None, True, False, False, False), ('pg_catalog', 'pg_statistic_ext_data', '***', None, True, False, False, False), ('public', 'dag_run', '***', None, True, False, True, False), ('public', 'task_fail', '***', None, True, False, True, False), ('pg_catalog', 'pg_largeobject', '***', None, True, False, False, False), ('pg_catalog', 'pg_user_mapping', '***', None, True, False, False, False), ('pg_catalog', 'pg_subscription', '***', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_attribute', '***', None, True, False, False, False), ('pg_catalog', 'pg_proc', '***', None, True, False, False, False), ('pg_catalog', 'pg_class', '***', None, True, False, False, False), ('pg_catalog', 'pg_attrdef', '***', None, True, False, False, False), ('pg_catalog', 'pg_constraint', '***', None, True, False, False, False), ('pg_catalog', 'pg_inherits', '***', None, True, False, False, False), ('pg_catalog', 'pg_index', '***', None, True, False, False, False), ('pg_catalog', 'pg_operator', '***', None, True, False, False, False), ('pg_catalog', 'pg_opfamily', '***', None, True, False, False, False), ('pg_catalog', 'pg_opclass', '***', None, True, False, False, False), ('pg_catalog', 'pg_am', '***', None, True, False, False, False), ('pg_catalog', 'pg_amop', '***', None, True, False, False, False), ('pg_catalog', 'pg_amproc', '***', None, True, False, False, False), ('pg_catalog', 'pg_language', '***', None, True, False, False, False), ('pg_catalog', 'pg_largeobject_metadata', '***', None, True, False, False, False), ('pg_catalog', 'pg_aggregate', '***', None, True, False, False, False), ('pg_catalog', 'pg_statistic_ext', '***', None, True, False, False, False), ('pg_catalog', 'pg_rewrite', '***', None, True, False, False, False), ('pg_catalog', 'pg_trigger', '***', None, True, False, False, False), ('pg_catalog', 'pg_event_trigger', '***', None, True, False, False, False), ('pg_catalog', 'pg_description', '***', None, True, False, False, False), ('pg_catalog', 'pg_cast', '***', None, True, False, False, False), ('pg_catalog', 'pg_enum', '***', None, True, False, False, False), ('pg_catalog', 'pg_namespace', '***', None, True, False, False, False), ('pg_catalog', 'pg_conversion', '***', None, True, False, False, False), ('pg_catalog', 'pg_depend', '***', None, True, False, False, False), ('pg_catalog', 'pg_database', '***', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_db_role_setting', '***', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_tablespace', '***', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_auth_members', '***', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_shdepend', '***', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_shdescription', '***', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_ts_config', '***', None, True, False, False, False), ('pg_catalog', 'pg_ts_config_map', '***', None, True, False, False, False), ('pg_catalog', 'pg_ts_dict', '***', None, True, False, False, False), ('pg_catalog', 'pg_ts_parser', '***', None, True, False, False, False), ('pg_catalog', 'pg_ts_template', '***', None, True, False, False, False), ('pg_catalog', 'pg_extension', '***', None, True, False, False, False), ('pg_catalog', 'pg_foreign_data_wrapper', '***', None, True, False, False, False), ('pg_catalog', 'pg_foreign_server', '***', None, True, False, False, False), ('pg_catalog', 'pg_policy', '***', None, True, False, False, False), ('pg_catalog', 'pg_replication_origin', '***', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_default_acl', '***', None, True, False, False, False), ('pg_catalog', 'pg_init_privs', '***', None, True, False, False, False), ('pg_catalog', 'pg_seclabel', '***', None, True, False, False, False), ('pg_catalog', 'pg_shseclabel', '***', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_collation', '***', None, True, False, False, False), ('pg_catalog', 'pg_partitioned_table', '***', None, True, False, False, False), ('pg_catalog', 'pg_range', '***', None, True, False, False, False), ('pg_catalog', 'pg_transform', '***', None, True, False, False, False), ('pg_catalog', 'pg_sequence', '***', None, True, False, False, False), ('pg_catalog', 'pg_publication', '***', None, True, False, False, False), ('pg_catalog', 'pg_publication_rel', '***', None, True, False, False, False), ('pg_catalog', 'pg_subscription_rel', '***', None, True, False, False, False), ('information_schema', 'sql_implementation_info', '***', None, False, False, False, False), ('information_schema', 'sql_parts', '***', None, False, False, False, False), ('information_schema', 'sql_sizing', '***', None, False, False, False, False), ('information_schema', 'sql_features', '***', None, False, False, False, False), ('public', 'serialized_dag', '***', None, True, False, False, False), ('public', 'rendered_task_instance_fields', '***', None, True, False, True, False), ('public', 'dag_tag', '***', None, True, False, True, False), ('public', 'task_reschedule', '***', None, True, False, True, False), ('public', 'dag_code', '***', None, True, False, False, False), ('public', 'ab_permission', '***', None, True, False, True, False), ('public', 'ab_permission_view', '***', None, True, False, True, False), ('public', 'ab_view_menu', '***', None, True, False, True, False), ('public', 'ab_permission_view_role', '***', None, True, False, True, False), ('public', 'ab_role', '***', None, True, False, True, False), ('public', 'ab_user', '***', None, True, False, True, False), ('public', 'ab_user_role', '***', None, True, False, True, False), ('public', 'ab_register_user', '***', None, True, False, False, False), ('public', 'sensor_instance', '***', None, True, False, False, False), ('public', 'trigger', '***', None, True, False, True, False), ('public', 'task_instance', '***', None, True, False, True, False), ('public', 'session', '***', None, True, False, False, False), ('public', 'log_template', '***', None, True, False, True, False), ('public', 'callback_request', '***', None, True, False, False, False), ('public', 'task_map', '***', None, True, False, True, False), ('public', 'xcom', '***', None, True, False, True, False), ('public', 'celery_taskmeta', '***', None, True, False, False, False), ('public', 'celery_tasksetmeta', '***', None, True, False, False, False), ('public', 'my_table', '***', None, False, False, False, False)]
[2022-09-08 17:41:50,879] {jobs_dag.py:67} INFO - THIS IS THE SCHEMA:
[2022-09-08 17:41:50,879] {jobs_dag.py:68} INFO - public
[2022-09-08 17:41:50,880] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobs_dag.py", line 72, in check_table_exist
    query = hook.get_first(sql=sql_to_check_table_exist.format(table_name))
IndexError: tuple index out of range
[2022-09-08 17:41:50,894] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=tables_name_1, task_id=check_table_exist, execution_date=20220908T174147, start_date=20220908T174150, end_date=20220908T174150
[2022-09-08 17:41:50,910] {standard_task_runner.py:97} ERROR - Failed to execute job 4042 for task check_table_exist (tuple index out of range; 5366)
[2022-09-08 17:41:50,925] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08 17:41:50,993] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
