[2022-09-07 16:41:46,637] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tables_name_1.check_table_exist manual__2022-09-07T16:41:43.194180+00:00 [queued]>
[2022-09-07 16:41:46,660] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tables_name_1.check_table_exist manual__2022-09-07T16:41:43.194180+00:00 [queued]>
[2022-09-07 16:41:46,661] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-07 16:41:46,661] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-07 16:41:46,662] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-07 16:41:46,684] {taskinstance.py:1397} INFO - Executing <Task(BranchPythonOperator): check_table_exist> on 2022-09-07 16:41:43.194180+00:00
[2022-09-07 16:41:46,691] {standard_task_runner.py:52} INFO - Started process 13001 to run task
[2022-09-07 16:41:46,695] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tables_name_1', 'check_table_exist', 'manual__2022-09-07T16:41:43.194180+00:00', '--job-id', '3931', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmp48yq5ln0', '--error-file', '/tmp/tmpii78wddj']
[2022-09-07 16:41:46,697] {standard_task_runner.py:80} INFO - Job 3931: Subtask check_table_exist
[2022-09-07 16:41:46,786] {task_command.py:371} INFO - Running <TaskInstance: tables_name_1.check_table_exist manual__2022-09-07T16:41:43.194180+00:00 [running]> on host eba23da77ca5
[2022-09-07 16:41:46,885] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tables_name_1
AIRFLOW_CTX_TASK_ID=check_table_exist
AIRFLOW_CTX_EXECUTION_DATE=2022-09-07T16:41:43.194180+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-07T16:41:43.194180+00:00
[2022-09-07 16:41:46,902] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-09-07 16:41:46,915] {jobs_dag.py:41} INFO - THIS IS FIRST QUERY:
[2022-09-07 16:41:46,917] {jobs_dag.py:42} INFO - [('pg_catalog', 'pg_statistic', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_type', 'julitorresma', None, True, False, False, False), ('public', 'dag_runs', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_foreign_table', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_authid', 'julitorresma', 'pg_global', True, False, False, False), ('public', 'my_table', 'julitorresma', None, False, False, False, False), ('pg_catalog', 'pg_statistic_ext_data', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_user_mapping', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_subscription', 'julitorresma', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_attribute', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_proc', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_class', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_attrdef', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_constraint', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_inherits', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_index', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_operator', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_opfamily', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_opclass', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_am', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_amop', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_amproc', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_language', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_largeobject_metadata', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_aggregate', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_statistic_ext', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_rewrite', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_trigger', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_event_trigger', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_description', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_cast', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_enum', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_namespace', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_conversion', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_depend', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_database', 'julitorresma', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_db_role_setting', 'julitorresma', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_tablespace', 'julitorresma', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_auth_members', 'julitorresma', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_shdepend', 'julitorresma', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_shdescription', 'julitorresma', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_ts_config', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_ts_config_map', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_ts_dict', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_ts_parser', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_ts_template', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_extension', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_foreign_data_wrapper', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_foreign_server', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_policy', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_replication_origin', 'julitorresma', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_default_acl', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_init_privs', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_seclabel', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_shseclabel', 'julitorresma', 'pg_global', True, False, False, False), ('pg_catalog', 'pg_collation', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_partitioned_table', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_range', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_transform', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_sequence', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_publication', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_publication_rel', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_subscription_rel', 'julitorresma', None, True, False, False, False), ('pg_catalog', 'pg_largeobject', 'julitorresma', None, True, False, False, False), ('information_schema', 'sql_parts', 'julitorresma', None, False, False, False, False), ('information_schema', 'sql_implementation_info', 'julitorresma', None, False, False, False, False), ('information_schema', 'sql_features', 'julitorresma', None, False, False, False, False), ('information_schema', 'sql_sizing', 'julitorresma', None, False, False, False, False)]
[2022-09-07 16:41:46,919] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobs_dag.py", line 51, in check_table_exist
    query = hook.get_first(sql=sql_to_check_table_exist.format(schema, table_name))
UnboundLocalError: local variable 'schema' referenced before assignment
[2022-09-07 16:41:46,933] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=tables_name_1, task_id=check_table_exist, execution_date=20220907T164143, start_date=20220907T164146, end_date=20220907T164146
[2022-09-07 16:41:46,948] {standard_task_runner.py:97} ERROR - Failed to execute job 3931 for task check_table_exist (local variable 'schema' referenced before assignment; 13001)
[2022-09-07 16:41:46,989] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-07 16:41:47,058] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
