[2022-08-17 15:32:47,492] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_dag.accurate manual__2022-08-17T15:32:42+00:00 [queued]>
[2022-08-17 15:32:47,508] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_dag.accurate manual__2022-08-17T15:32:42+00:00 [queued]>
[2022-08-17 15:32:47,509] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 15:32:47,510] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-17 15:32:47,511] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 15:32:47,530] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): accurate> on 2022-08-17 15:32:42+00:00
[2022-08-17 15:32:47,536] {standard_task_runner.py:52} INFO - Started process 2381 to run task
[2022-08-17 15:32:47,541] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'manual__2022-08-17T15:32:42+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpf5xpuc7p', '--error-file', '/tmp/tmp21y_aslf']
[2022-08-17 15:32:47,542] {standard_task_runner.py:80} INFO - Job 69: Subtask accurate
[2022-08-17 15:32:47,639] {task_command.py:371} INFO - Running <TaskInstance: my_dag.accurate manual__2022-08-17T15:32:42+00:00 [running]> on host 9d5d2a77e6ba
[2022-08-17 15:32:47,751] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T15:32:42+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T15:32:42+00:00
[2022-08-17 15:32:47,754] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-17 15:32:47,756] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2022-08-17 15:32:47,773] {subprocess.py:85} INFO - Output:
[2022-08-17 15:32:47,776] {subprocess.py:92} INFO - accurate
[2022-08-17 15:32:47,777] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-17 15:32:47,817] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20220817T153242, start_date=20220817T153247, end_date=20220817T153247
[2022-08-17 15:32:47,878] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-17 15:32:47,925] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
